print("Hey there")
input()
a=input("want to play a game")
if a.lower()=='no':
  exit()
print("think about a number between 0-20, for easy calculation")
input()
print("do calculations in your mind, don't tell to me")
input()
print("now suppose your friend gave you the same number and your number got double")
input()
print("now I gave you 10, add the 10 in that number")
input()
print("you donated the 50% of the number")
input()
print("your friend is asking for the amount he gave you, he want it back")
input()
print("subtract 2 from the number you have")
input()
print("you have number '3' left")
